name: 🚀 Deploy front

on:
  push:
    branches:
      [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Baixar Dependencias
      run: npm install /var/www/html/_work/infinityflow-frontend/infinityflow-frontend/src
        
    - name: Reload Daemon
      run: sudo systemctl daemon-reload

    - name: Restart Frontend Service
      run: sudo systemctl restart infinityflow-frontend.service
      
